
CREATE TABLE IF NOT EXISTS public.favorites
(
    fav_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id integer NOT NULL,
    CONSTRAINT fk_account FOREIGN KEY (account_id)
    REFERENCES public.account (account_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.favorite_items
(
    fav_item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fav_id integer NOT NULL, 
    inv_id integer NOT NULL,
    fav_item_note text, 
    CONSTRAINT fk_favorite FOREIGN KEY (fav_id)
    REFERENCES public.favorites (fav_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT fk_inventory FOREIGN KEY (inv_id)
    REFERENCES public.inventory (inv_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT unique_favorite_item UNIQUE (fav_id, inv_id)
);

